### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by aalbino2** [FAIRmat-NFDI/nomad-distribution-template#16]
The repo template works nicely, I had a small misunderstanding with the docker-compose.yaml file:

I was modifying the one in the repo and didn't realize that I should have downloaded it and placed it in my unzipped folder

We should indicate it in the docs in some way, for newbies like me. A sentence would be enough. What do you think @hampusnasstrom ?

**Comment by hampusnasstrom** [comment]
Ah, yeah. That might be good. I could even delete it after putting it in the zip?

**Comment by aalbino2** [comment]
you mean delete it from the repo?

**Comment by hampusnasstrom** [comment]
Yeah, since you will have to change it locally if you want to change it anyways.

**Comment by aalbino2** [comment]
I'm not sure, it might be nice to keep it there, if you want to share with someone your repo and tell to download it.

Can it be placed in a folder maybe? Or even there is fine. Just expliciting its use in the docs would be okay

**Comment by blueraft** [comment]
I think this is not relevant anymore since the docker compose file is now part of the repo.
